syntax = "proto3";

package machugi.board;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "machugi/board/common.proto";

service NoticeGrpcService {
  rpc GetNoticeList(GrpcPagingRequest) returns (GrpcNoticePageResponse) {
    option (google.api.http) = {get: "/api/notice"};
  }

  rpc AddNotice(GrpcUpsertNoticeRequest) returns (GrpcNoticeDetailResponse) {
    option (google.api.http) = {
      post: "/api/notice"
      body: "*"
    };
  }

  rpc GetNoticeDetail(GrpcBoardIdxRequest) returns (GrpcNoticeDetailResponse) {
    option (google.api.http) = {get: "/api/notice/{board_idx}"};
  }

  rpc UpdateNotice(GrpcUpsertNoticeRequest) returns (GrpcNoticeDetailResponse) {
    option (google.api.http) = {
      put: "/api/notice/{board_idx}"
      body: "*"
    };
  }

  rpc DeleteNotice(GrpcBoardIdxRequest) returns (GrpcNoticePageResponse) {
    option (google.api.http) = {delete: "/api/notice/{board_idx}"};
  }
}

message GrpcNoticeListResponse {
  uint64 idx = 1;
  string title = 2;
  BoardState state = 3;
  int32 view_count = 4;
  bool is_pinned = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message GrpcNoticeDetailResponse {
  uint64 idx = 1;
  string title = 2;
  BoardState state = 3;
  int32 view_count = 4;
  bool is_pinned = 5;
  google.protobuf.Timestamp updated_at = 6;
  string content = 7;
}

message GrpcNoticePageResponse {
  repeated GrpcNoticeListResponse items = 1;

  int32 total_count = 2;
  int32 current_page = 3;
  int32 total_pages = 4;
  bool has_next = 5;
}

message GrpcUpsertNoticeRequest {
  string title = 1;
  BoardState state = 2;
  bool is_pinned = 3;
  string content = 4;

  optional uint64 board_idx = 5;
}

message GrpcBoardIdxRequest {
  uint64 board_idx = 1;
}
