spring:
  application:
    name: user

  # 테스트용 (h2)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

custom:
  jwt:
    # 로컬 환경에서의 테스트 할 키 (유출되도 상관 X)
    secrets: "thisIsMyLocalTestSecretKeyForJwtTokenGeneration12345"