spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

custom:
  jwt:
    # 로컬 환경에서의 테스트 할 키 (유출되도 상관 X)
    secrets: "thisIsMyLocalTestSecretKeyForJwtTokenGeneration12345"