name: envoy

services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    ports:
      - "8080:8080"  # 게이트웨이
      - "9901:9901"  # 관리자 페이지
    volumes:
      - ./envoy/envoy-user.yml:/etc/envoy/envoy-user.yaml
      - ./envoy/descriptor.pb:/tmp/descriptor.pb
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
